disabled_rules:
  - todo
opt_in_rules:
  - force_unwrapping
  - trailing_whitespace
  - vertical_whitespace
  - file_length
  - function_body_length
  - type_body_length
included:
  - Sources
  - Tests
excluded:
  - .build
  - Package.swift
function_body_length:
  warning: 80
  error: 120
reporter: "xcode"
